<?php
// @codingStandardsIgnoreFile
/** @var Troya\Comments\Block\Product\View\ListView $block */

$allItems = $block->getReviewItemsFiltered();
$_items = $allItems['questions'];
$_answerItems = $allItems['answers'];
$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
$relations = $block->getRelationsTree();

?>
<?php if (count($_items)): ?>
    <div class="block review-list" id="customer-reviews">
        <div class="block-title">
            <strong><?= $block->escapeHtml(__('Customer Reviews')) ?></strong>
        </div>
        <div class="block-content">
            <div class="toolbar review-toolbar">
                <?= $block->getChildHtml('toolbar') ?>
            </div>
            <ol class="items review-items">
                <?php foreach ($_items as $_reviewId): ?>
                    <?php $_review = $block->getReviewData($_reviewId); ?>
                    <li class="item review-item" itemscope itemprop="review" itemtype="http://schema.org/Review"
                        item-rew-id="<?= $_review->getId() ?>">
                        <div class="review-title" itemprop="name"><?= $block->escapeHtml($_review->getTitle()) ?></div>
                        <?php if (count($_review->getRatingVotes())): ?>
                            <div class="review-ratings">
                                <?php foreach ($_review->getRatingVotes() as $_vote): ?>
                                    <div class="rating-summary item" itemprop="reviewRating" itemscope
                                         itemtype="http://schema.org/Rating">
                                        <span class="label rating-label"><span><?= $block->escapeHtml($_vote->getRatingCode()) ?></span></span>
                                        <div class="rating-result"
                                             title="<?= $block->escapeHtmlAttr($_vote->getPercent()) ?>%">
                                            <meta itemprop="worstRating" content="1"/>
                                            <meta itemprop="bestRating" content="100"/>
                                            <span style="width:<?= $block->escapeHtmlAttr($_vote->getPercent()) ?>%">
                                <span itemprop="ratingValue"><?= $block->escapeHtml($_vote->getPercent()) ?>%</span>
                            </span>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        <?php endif; ?>
                        <div class="review-content" itemprop="description">
                            <?= nl2br($block->escapeHtml($_review->getDetail())) ?>
                        </div>
                        <div class="review-details">
                            <p class="review-author">
                                <span class="review-details-label"><?= $block->escapeHtml(__('Review by')) ?></span>
                                <strong class="review-details-value"
                                        itemprop="author"><?= $block->escapeHtml($_review->getNickname()) ?></strong>
                            </p>
                            <p class="review-date">
                                <span class="review-details-label"><?= $block->escapeHtml(__('Posted on')) ?></span>
                                <time class="review-details-value" itemprop="datePublished"
                                      datetime="<?= $block->escapeHtmlAttr($block->formatDate($_review->getCreatedAt(), $format)) ?>"><?= $block->escapeHtml($block->formatDate($_review->getCreatedAt(), $format)) ?></time>
                            </p>
                        </div>

                        <?php if (isset($relations[$_review->getId()])): ?>
                            <?php foreach ($relations[$_review->getId()] as $keyRes => $responseId): ?>
                                <?php if (in_array($responseId, $_answerItems)): ?>
                                    <?php $answer = $block->getReviewData($responseId); ?>
                                    <div class="troya-comments-reply item">
                                        <label for="answer-<?= $answer->getId() ?>"><?= __('Reply From') ?> <?= $block->escapeHtml($answer->getNickname()) ?></label>
                                        <div class="review-content troya-comments" itemprop="description"
                                             id="answer-<?= $answer->getId() ?>">
                                            <?= nl2br($block->escapeHtml($answer->getDetail())) ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        <?php endif; ?>

                        <div class="troya-comments buttons-set">
                            <button class="troya-reply" id="<?= $_review->getId() ?>"><?= __('Reply') ?></button>
                            <button class="troya-cancel" id="<?= $_review->getId() ?>"><?= __('Cancel') ?></button>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <div class="toolbar review-toolbar">
                <?= $block->getChildHtml('toolbar') ?>
            </div>


        </div>
    </div>
<?php endif; ?>